services:
  grok2api:
    image: verofess/grok2api
    container_name: grok2api
    environment:
      - API_KEY=sk-api-key-demo-you-should-change-it
      - IS_TEMP_CONVERSATION=true
      - SHOW_SEARCH_RESULTS=true
      - SHOW_THINKING=true
    volumes:
      - ./data:/data
    ports:
      - 5200:5200